### ISSUE TITLE
Serilog.Sinks.Splunk active maintainer

### ISSUE THREAD

**Issue by EEParker** [serilog-contrib/home#8]
Hello, [Serilog.Sinks.Splunk ](https://github.com/serilog-contrib/serilog-sinks-splunk) has not had an active maintainer in 3+ years. Is it possible to transfer this Repo to an active maintainer? I would be willing to volunteer if the organization does not have anyone to approve pull requests.

Thank you for your time.

**Comment by augustoproiete** [comment]
Hey @EEParker I'm following up on this issue after recent access/permissions updates on the [serilog-sinks-splunk](https://github.com/serilog-contrib/serilog-sinks-splunk) repo.

As per request from @merbla, you (@EEParker) now have access to the repo.

@nblumhardt Also reached out about @VictorioBerra offering to help, and he now also has write access to the repo as of this writing.

You guys can coordinate your efforts from here ([looks like you are already doing it, great stuff](https://github.com/serilog-contrib/serilog-sinks-splunk/pull/172))

**Comment by EEParker** [comment]
Thank you
